// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ00xbu9hH_KwL6NS8y57X6HhDFfymfns',
    appId: '1:513620500449:web:6f314c1010998f5010bca0',
    messagingSenderId: '513620500449',
    projectId: 'fruits-hub-2d546',
    authDomain: 'fruits-hub-2d546.firebaseapp.com',
    storageBucket: 'fruits-hub-2d546.appspot.com',
    measurementId: 'G-TE9WY01MZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhdeEtppPMd-5d48sRItkqp4s4Bvqmf-o',
    appId: '1:513620500449:android:847752a82ed3fdcf10bca0',
    messagingSenderId: '513620500449',
    projectId: 'fruits-hub-2d546',
    storageBucket: 'fruits-hub-2d546.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1z1e4bXOgduAOML378SK_fM2k8OOtTPg',
    appId: '1:513620500449:ios:9f6355e9aa2e527310bca0',
    messagingSenderId: '513620500449',
    projectId: 'fruits-hub-2d546',
    storageBucket: 'fruits-hub-2d546.appspot.com',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1z1e4bXOgduAOML378SK_fM2k8OOtTPg',
    appId: '1:513620500449:ios:9f6355e9aa2e527310bca0',
    messagingSenderId: '513620500449',
    projectId: 'fruits-hub-2d546',
    storageBucket: 'fruits-hub-2d546.appspot.com',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ00xbu9hH_KwL6NS8y57X6HhDFfymfns',
    appId: '1:513620500449:web:40eab91d73fabf9710bca0',
    messagingSenderId: '513620500449',
    projectId: 'fruits-hub-2d546',
    authDomain: 'fruits-hub-2d546.firebaseapp.com',
    storageBucket: 'fruits-hub-2d546.appspot.com',
    measurementId: 'G-94ST4M9DSN',
  );
}
